#!/usr/bin/env bash
# ex ./setvolume 40

BASE_VOLUME='30%'
VOLUME=$1

if [ "$1" == "level" ]; then
	for SINK in $(pactl list sinks | grep 'Sink #' | cut -b7-); do
		pactl set-sink-volume $SINK $BASE_VOLUME #Set all sinks to BASE_VOLUME
	done
	exit 1
fi

for SINK in $(pactl list sinks | grep 'Sink #' | cut -b7-); do
	pactl set-sink-volume "$SINK" "$VOLUME%"
done
